# NOTE: update this with your service name
service: lunch-picker-server

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  webpackIncludeModules:
    forceInclude:
      - mysql
      - mysql2

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2
  environment:
    YELP_API_KEY: 'kIR0vzSzmSfa8WkdTAMzj5PMDHIu9ukrN-x_wu3POdAFy-zzEBkCXj6wvH2FXjeoFWTGIx7ZNJn6e7NgSx-eG1tnEVKz4-fmtoTK-5kgDdMiC2apRZXxkcBFOhrbWnYx'
  vpc:
    securityGroupIds:
      - sg-07e7f48a7af8a95f3
    subnetIds:
      - subnet-0e542247
      - subnet-242ed57c
      - subnet-fe0f4b99
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface 
        - rekognition:DetectText	
      Resource: "*"

functions:
  create:
    handler: api/create.handler
    events:
      - http:
          path: restaurants
          method: post
          cors: true
          authorizer: aws_iam

  get:
    handler: api/get.handler
    events:
      - http:
          path: restaurants/{id}
          method: get
          cors: true
          authorizer: aws_iam

  update:
    handler: api/update.handler
    events:
      - http:
          path: restaurants/{id}
          method: put
          cors: true
          authorizer: aws_iam
  
  delete:
    handler: api/delete.handler
    events:
      - http:
          path: restaurants/{id}
          method: delete
          cors: true
          authorizer: aws_iam

  list:
    handler: api/list.handler
    events:
      - http:
          path: restaurants
          method: get
          cors: true
          authorizer: aws_iam

  detect:
    handler: api/detect.handler
    events:
      - http:
          path: restaurants/detect
          method: get
          cors: true
          authorizer: aws_iam

  yelpSearch:
    handler: api/yelp/search.handler
    events:
      - http:
          path: external/search
          method: get
          cors: true
          authorizer: aws_iam
    
  yelpGet:
    handler: api/yelp/get.handler
    events:
      - http:
          path: external/get/{id}
          method: get
          cors: true
          authorizer: aws_iam
  

